//! The Diesel table definitions, matching `migrations/0001_init`. Hand-written (the
//! schema is small and stable) rather than generated by `diesel print-schema`.

diesel::table! {
    movies (imdb_id) {
        imdb_id -> Text,
        tmdb_id -> Nullable<BigInt>,
        title -> Text,
        year -> Nullable<Integer>,
        overview -> Nullable<Text>,
        poster_url -> Nullable<Text>,
        backdrop_url -> Nullable<Text>,
        runtime_min -> Nullable<BigInt>,
        genres -> Text,
        rating -> Nullable<Double>,
        tmdb_json -> Nullable<Text>,
        added_at -> BigInt,
        last_used_at -> BigInt,
    }
}

diesel::table! {
    torrents (info_hash) {
        info_hash -> Text,
        imdb_id -> Text,
        magnet -> Text,
        size_bytes -> BigInt,
        video_file_idx -> BigInt,
        video_file_name -> Text,
        added_at -> BigInt,
        private -> Bool,
        download_limit -> Nullable<BigInt>,
        upload_limit -> Nullable<BigInt>,
        peer_limit -> Nullable<BigInt>,
        completed_at -> Nullable<BigInt>,
    }
}

diesel::table! {
    events (id) {
        id -> Integer,
        ts -> BigInt,
        kind -> Text,
        message -> Text,
    }
}

diesel::joinable!(torrents -> movies (imdb_id));
diesel::allow_tables_to_appear_in_same_query!(movies, torrents, events);
